server:
  port: 9003

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:eureka@eureka7001:7001/eureka/,http://eureka:eureka@eureka7002:7002/eureka/,http://eureka:eureka@eureka7003:7003/eureka/
      
      